name: CI
on:
  push:
jobs:
  build:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        env:
          GH_TOKEN: ${{ github.token }}
        run: |

          gh_debug() {
            echo "gh $@"
            gh "$@" > out 2> err || true
            cat $out
            echo
            cat $err
            echo
          }

          (
          echo '```'
          (
            gh_debug api /repos/$GITHUB_REPOSITORY/code-scanning/sarifs \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -f commit_sha=0000000000000000000000000000000000000000 \
              -f ref=refs/tags/check-spelling-sarif-pre-flight-test \
              -f sarif=""
  
            gh_debug api /repos/$GITHUB_REPOSITORY/code-scanning/codeql-action/features

            gh_debug api "/repos/$GITHUB_REPOSITORY/code-scanning/analysis" \
              --method PUT \
              -H "Accept: application/vnd.github+json" \
              -f commit_sha=0000000000000000000000000000000000000000 \
              -f ref=refs/tags/check-spelling-sarif-pre-flight-test \
              -f sarif=""
          )
          echo '```'
          ) | tee -a $GITHUB_STEP_SUMMARY
