name: CI
on:
  push:
jobs:
  build:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          (
          echo '```'
          gh api /repos/$GITHUB_REPOSITORY/code-scanning/sarifs \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -f commit_sha=0000000000000000000000000000000000000000 \
            -f ref=refs/tags/check-spelling-sarif-pre-flight-test \
            -f sarif="" 2>&1 || true
          echo '```'
          ) | tee -a $GITHUB_STEP_SUMMARY
